### ISSUE TITLE
Should be top-justified

### ISSUE THREAD

**Issue by ScottESanDiego** [Rabenauge/AmigaWebGuru#1]
Shouldn't this appear horizontally centered at the top of the page, not vertically centered?

**Comment by Rabenauge** [comment]
This I see as matter of  taste - isn´t it ?  ;)  

Well, if you want to change the vertical position of the shown error you just need to change the css style for body "height"  in the index.html at line 27. from height: 100vh; to  height: 0%;

I also added this to the README.md , now .  :)
